platform :ios, '9.0'

target 'easer' do

   use_frameworks!
    pod 'Firebase/Core', '~> 5.20.2'
    pod 'Firebase/Auth', '~> 5.20.2'
    pod 'Firebase/Database', '~> 5.20.2'
    pod 'Firebase/Firestore', '~> 5.20.2'


    # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    target 'easerTests' do
        inherit! :search_paths
        # Pods for testing
    end
end

target 'easer-tvOS' do
  use_frameworks!

  target 'easer-tvOSTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")
end
